baseURL = "/"
languageCode = "en-us"
publishDir = "docs"
title = "Ben Adams' Design Portfolio"

[params] # theme parameters
    
    tagline = "Ben Adams, Designer + Developer" # Splash Intro Text
    info = "Based in D.C., I've been building stuff on the web for close to a decade. I like to stay involved from start-to-finish, combining user-centered design principles with a passion for writing clean, accessible code."
    description = "An online portfolio showcasing the work and professional experience of designer and developer Ben Adams" # site description"
    keywords = "UI, UX, User Experience, Frontend Development, Mockups, Wireframes, Prototypes, React, HTML, CSS, JS" # site keywords"
    author = "Bennett (Ben) Adams"
    # wether you want to hide copyright in footer
    hideCopyright = false
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/beadams86"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/beadams86"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/beadams86"

# Menu links
[[menu.main]]
    title = "Ben Adams' Design Portfolio"
    name = "Portfolio"
    weight = 1
    url  = "/"
[[menu.main]]
    title = "About Designer Ben Adams"
    name = "About"
    weight = 2
    url = "/about/"

    SectionPagesMenu = "main"