baseURL = "/"
languageCode = "en-us"

[params] # theme parameters
    tagline = "Ben Adams, Engineering Design" # Splash Intro Text
    info = "I'm a Designer and Developer living in Washington DC. As a designer with a passion for clean code, I go beyond wireframes, mockups, and diagrams."
    description = "Ben Adams' Design Portfolio" # site description"
    keywords = "UI, UX, User Experience, Frontend Development, Mockups, Wireframes, Prototypes, React, HTML, CSS, JS" # site keywords"
    author = "Bennett (Ben) Adams"
    # wether you want to hide copyright in footer
    hideCopyright = false
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/beadams86"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/beadams86"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/beadams86"

# Menu links
[[menu.main]]
    name = "Portfolio"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

    SectionPagesMenu = "main"